# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileBar.ui'
#
# Created: Wed Jul 13 15:20:35 2011
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(673, 183)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.fabFileLabel = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fabFileLabel.sizePolicy().hasHeightForWidth())
        self.fabFileLabel.setSizePolicy(sizePolicy)
        self.fabFileLabel.setMinimumSize(QtCore.QSize(50, 14))
        self.fabFileLabel.setBaseSize(QtCore.QSize(50, 14))
        self.fabFileLabel.setObjectName("fabFileLabel")
        self.horizontalLayout_10.addWidget(self.fabFileLabel)
        self.fabFileLineEdit = QtGui.QLineEdit(Form)
        self.fabFileLineEdit.setReadOnly(True)
        self.fabFileLineEdit.setObjectName("fabFileLineEdit")
        self.horizontalLayout_10.addWidget(self.fabFileLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timeLabel = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        self.timeLabel.setBaseSize(QtCore.QSize(50, 14))
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout_2.addWidget(self.timeLabel)
        self.timeSpinBox = QtGui.QSpinBox(Form)
        self.timeSpinBox.setEnabled(True)
        self.timeSpinBox.setReadOnly(True)
        self.timeSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.timeSpinBox.setMaximum(100000)
        self.timeSpinBox.setProperty("value", QtCore.QVariant(0))
        self.timeSpinBox.setObjectName("timeSpinBox")
        self.horizontalLayout_2.addWidget(self.timeSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.volumeTreeWidget = QtGui.QTreeWidget(Form)
        self.volumeTreeWidget.setMinimumSize(QtCore.QSize(191, 0))
        self.volumeTreeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.volumeTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.volumeTreeWidget.setAutoScrollMargin(15)
        self.volumeTreeWidget.setProperty("showDropIndicator", QtCore.QVariant(False))
        self.volumeTreeWidget.setAlternatingRowColors(True)
        self.volumeTreeWidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.volumeTreeWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.volumeTreeWidget.setAutoExpandDelay(-1)
        self.volumeTreeWidget.setIndentation(10)
        self.volumeTreeWidget.setRootIsDecorated(False)
        self.volumeTreeWidget.setAllColumnsShowFocus(True)
        self.volumeTreeWidget.setObjectName("volumeTreeWidget")
        self.volumeTreeWidget.header().setDefaultSectionSize(100)
        self.horizontalLayout.addWidget(self.volumeTreeWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.changeFilePushButton = QtGui.QPushButton(Form)
        self.changeFilePushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.changeFilePushButton.setObjectName("changeFilePushButton")
        self.verticalLayout_2.addWidget(self.changeFilePushButton)
        self.fabFileLabel.setBuddy(self.fabFileLineEdit)
        self.timeLabel.setBuddy(self.timeSpinBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("Form", "Set and Review File", None, QtGui.QApplication.UnicodeUTF8))
        self.fabFileLabel.setText(QtGui.QApplication.translate("Form", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLabel.setText(QtGui.QApplication.translate("Form", "Total Time", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSpinBox.setSuffix(QtGui.QApplication.translate("Form", " S", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("Form", "Materials", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("Form", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.changeFilePushButton.setText(QtGui.QApplication.translate("Form", "Change File", None, QtGui.QApplication.UnicodeUTF8))

