# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JogBar.ui'
#
# Created: Wed Jul 13 21:46:56 2011
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(655, 342)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.messageEdit = QtGui.QLineEdit(Form)
        self.messageEdit.setFrame(False)
        self.messageEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.messageEdit.setReadOnly(True)
        self.messageEdit.setObjectName("messageEdit")
        self.verticalLayout_3.addWidget(self.messageEdit)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.topLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.topLabel.setFont(font)
        self.topLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel.setObjectName("topLabel")
        self.gridLayout_4.addWidget(self.topLabel, 0, 2, 1, 1)
        self.ulPushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ulPushButton.sizePolicy().hasHeightForWidth())
        self.ulPushButton.setSizePolicy(sizePolicy)
        self.ulPushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.ulPushButton.setBaseSize(QtCore.QSize(40, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Arrow/Aiga_forwardandleftarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ulPushButton.setIcon(icon)
        self.ulPushButton.setObjectName("ulPushButton")
        self.gridLayout_4.addWidget(self.ulPushButton, 1, 1, 1, 1)
        self.upPushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upPushButton.sizePolicy().hasHeightForWidth())
        self.upPushButton.setSizePolicy(sizePolicy)
        self.upPushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.upPushButton.setBaseSize(QtCore.QSize(40, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Arrow/Aiga_uparrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upPushButton.setIcon(icon1)
        self.upPushButton.setIconSize(QtCore.QSize(30, 30))
        self.upPushButton.setAutoRepeat(True)
        self.upPushButton.setAutoExclusive(True)
        self.upPushButton.setObjectName("upPushButton")
        self.gridLayout_4.addWidget(self.upPushButton, 1, 2, 1, 1)
        self.urPushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urPushButton.sizePolicy().hasHeightForWidth())
        self.urPushButton.setSizePolicy(sizePolicy)
        self.urPushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.urPushButton.setBaseSize(QtCore.QSize(40, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Arrow/Aiga_forwardandrightarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.urPushButton.setIcon(icon2)
        self.urPushButton.setObjectName("urPushButton")
        self.gridLayout_4.addWidget(self.urPushButton, 1, 3, 1, 1)
        self.leftLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.leftLabel.setFont(font)
        self.leftLabel.setObjectName("leftLabel")
        self.gridLayout_4.addWidget(self.leftLabel, 2, 0, 1, 1)
        self.rightPushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightPushButton.sizePolicy().hasHeightForWidth())
        self.rightPushButton.setSizePolicy(sizePolicy)
        self.rightPushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.rightPushButton.setBaseSize(QtCore.QSize(40, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Arrow/Aiga_leftarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightPushButton.setIcon(icon3)
        self.rightPushButton.setIconSize(QtCore.QSize(30, 30))
        self.rightPushButton.setObjectName("rightPushButton")
        self.gridLayout_4.addWidget(self.rightPushButton, 2, 1, 1, 1)
        self.rightLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.rightLabel.setFont(font)
        self.rightLabel.setObjectName("rightLabel")
        self.gridLayout_4.addWidget(self.rightLabel, 2, 4, 1, 1)
        self.dlPushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dlPushButton.sizePolicy().hasHeightForWidth())
        self.dlPushButton.setSizePolicy(sizePolicy)
        self.dlPushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.dlPushButton.setBaseSize(QtCore.QSize(40, 40))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Arrow/Aiga_leftanddownarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dlPushButton.setIcon(icon4)
        self.dlPushButton.setObjectName("dlPushButton")
        self.gridLayout_4.addWidget(self.dlPushButton, 3, 1, 1, 1)
        self.downPushbutton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downPushbutton.sizePolicy().hasHeightForWidth())
        self.downPushbutton.setSizePolicy(sizePolicy)
        self.downPushbutton.setMinimumSize(QtCore.QSize(80, 80))
        self.downPushbutton.setBaseSize(QtCore.QSize(40, 40))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Arrow/Aiga_downarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downPushbutton.setIcon(icon5)
        self.downPushbutton.setIconSize(QtCore.QSize(30, 30))
        self.downPushbutton.setObjectName("downPushbutton")
        self.gridLayout_4.addWidget(self.downPushbutton, 3, 2, 1, 1)
        self.drPushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drPushButton.sizePolicy().hasHeightForWidth())
        self.drPushButton.setSizePolicy(sizePolicy)
        self.drPushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.drPushButton.setBaseSize(QtCore.QSize(40, 40))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Arrow/Aiga_rightanddownarrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drPushButton.setIcon(icon6)
        self.drPushButton.setObjectName("drPushButton")
        self.gridLayout_4.addWidget(self.drPushButton, 3, 3, 1, 1)
        self.bottomLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.bottomLabel.setFont(font)
        self.bottomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bottomLabel.setObjectName("bottomLabel")
        self.gridLayout_4.addWidget(self.bottomLabel, 4, 2, 1, 1)
        self.leftPushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftPushButton.sizePolicy().hasHeightForWidth())
        self.leftPushButton.setSizePolicy(sizePolicy)
        self.leftPushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.leftPushButton.setBaseSize(QtCore.QSize(40, 40))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Arrow/Aiga_rightarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftPushButton.setIcon(icon7)
        self.leftPushButton.setIconSize(QtCore.QSize(30, 30))
        self.leftPushButton.setObjectName("leftPushButton")
        self.gridLayout_4.addWidget(self.leftPushButton, 2, 3, 1, 1)
        self.toOriginButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toOriginButton.sizePolicy().hasHeightForWidth())
        self.toOriginButton.setSizePolicy(sizePolicy)
        self.toOriginButton.setMinimumSize(QtCore.QSize(80, 80))
        self.toOriginButton.setBaseSize(QtCore.QSize(40, 40))
        self.toOriginButton.setIconSize(QtCore.QSize(30, 30))
        self.toOriginButton.setObjectName("toOriginButton")
        self.gridLayout_4.addWidget(self.toOriginButton, 2, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.zTopLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.zTopLabel.setFont(font)
        self.zTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zTopLabel.setObjectName("zTopLabel")
        self.verticalLayout_2.addWidget(self.zTopLabel)
        self.minusZPushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minusZPushButton.sizePolicy().hasHeightForWidth())
        self.minusZPushButton.setSizePolicy(sizePolicy)
        self.minusZPushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.minusZPushButton.setIcon(icon1)
        self.minusZPushButton.setIconSize(QtCore.QSize(40, 40))
        self.minusZPushButton.setObjectName("minusZPushButton")
        self.verticalLayout_2.addWidget(self.minusZPushButton)
        self.plusZPushButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plusZPushButton.sizePolicy().hasHeightForWidth())
        self.plusZPushButton.setSizePolicy(sizePolicy)
        self.plusZPushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.plusZPushButton.setBaseSize(QtCore.QSize(50, 100))
        self.plusZPushButton.setIcon(icon5)
        self.plusZPushButton.setIconSize(QtCore.QSize(40, 40))
        self.plusZPushButton.setObjectName("plusZPushButton")
        self.verticalLayout_2.addWidget(self.plusZPushButton)
        self.zBottomLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.zBottomLabel.setFont(font)
        self.zBottomLabel.setText("Z+")
        self.zBottomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zBottomLabel.setObjectName("zBottomLabel")
        self.verticalLayout_2.addWidget(self.zBottomLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.incrementLabel = QtGui.QLabel(Form)
        self.incrementLabel.setObjectName("incrementLabel")
        self.gridLayout_3.addWidget(self.incrementLabel, 0, 1, 1, 1)
        self.commandedLabel = QtGui.QLabel(Form)
        self.commandedLabel.setObjectName("commandedLabel")
        self.gridLayout_3.addWidget(self.commandedLabel, 0, 3, 1, 1)
        self.xLabel = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xLabel.sizePolicy().hasHeightForWidth())
        self.xLabel.setSizePolicy(sizePolicy)
        self.xLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xLabel.setObjectName("xLabel")
        self.gridLayout_3.addWidget(self.xLabel, 1, 0, 1, 1)
        self.xIncrementSpin = QtGui.QDoubleSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xIncrementSpin.sizePolicy().hasHeightForWidth())
        self.xIncrementSpin.setSizePolicy(sizePolicy)
        self.xIncrementSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.xIncrementSpin.setBaseSize(QtCore.QSize(0, 25))
        self.xIncrementSpin.setSuffix(" mm")
        self.xIncrementSpin.setMaximum(400.0)
        self.xIncrementSpin.setProperty("value", QtCore.QVariant(1.0))
        self.xIncrementSpin.setObjectName("xIncrementSpin")
        self.gridLayout_3.addWidget(self.xIncrementSpin, 1, 1, 1, 1)
        self.xCommandSpin = QtGui.QDoubleSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xCommandSpin.sizePolicy().hasHeightForWidth())
        self.xCommandSpin.setSizePolicy(sizePolicy)
        self.xCommandSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.xCommandSpin.setBaseSize(QtCore.QSize(0, 25))
        self.xCommandSpin.setSuffix(" mm")
        self.xCommandSpin.setMinimum(-400.0)
        self.xCommandSpin.setMaximum(400.0)
        self.xCommandSpin.setObjectName("xCommandSpin")
        self.gridLayout_3.addWidget(self.xCommandSpin, 1, 3, 1, 1)
        self.yLabel = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yLabel.sizePolicy().hasHeightForWidth())
        self.yLabel.setSizePolicy(sizePolicy)
        self.yLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yLabel.setObjectName("yLabel")
        self.gridLayout_3.addWidget(self.yLabel, 3, 0, 1, 1)
        self.yIncrementSpin = QtGui.QDoubleSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yIncrementSpin.sizePolicy().hasHeightForWidth())
        self.yIncrementSpin.setSizePolicy(sizePolicy)
        self.yIncrementSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.yIncrementSpin.setBaseSize(QtCore.QSize(0, 25))
        self.yIncrementSpin.setSuffix(" mm")
        self.yIncrementSpin.setMaximum(400.0)
        self.yIncrementSpin.setProperty("value", QtCore.QVariant(1.0))
        self.yIncrementSpin.setObjectName("yIncrementSpin")
        self.gridLayout_3.addWidget(self.yIncrementSpin, 3, 1, 1, 1)
        self.yCommandSpin = QtGui.QDoubleSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yCommandSpin.sizePolicy().hasHeightForWidth())
        self.yCommandSpin.setSizePolicy(sizePolicy)
        self.yCommandSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.yCommandSpin.setBaseSize(QtCore.QSize(0, 25))
        self.yCommandSpin.setSuffix(" mm")
        self.yCommandSpin.setMinimum(-400.0)
        self.yCommandSpin.setMaximum(400.0)
        self.yCommandSpin.setObjectName("yCommandSpin")
        self.gridLayout_3.addWidget(self.yCommandSpin, 3, 3, 1, 1)
        self.zLabel = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zLabel.sizePolicy().hasHeightForWidth())
        self.zLabel.setSizePolicy(sizePolicy)
        self.zLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zLabel.setObjectName("zLabel")
        self.gridLayout_3.addWidget(self.zLabel, 5, 0, 1, 1)
        self.zIncrementSpin = QtGui.QDoubleSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zIncrementSpin.sizePolicy().hasHeightForWidth())
        self.zIncrementSpin.setSizePolicy(sizePolicy)
        self.zIncrementSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.zIncrementSpin.setBaseSize(QtCore.QSize(0, 25))
        self.zIncrementSpin.setSuffix(" mm")
        self.zIncrementSpin.setMinimum(0.0)
        self.zIncrementSpin.setMaximum(400.0)
        self.zIncrementSpin.setProperty("value", QtCore.QVariant(1.0))
        self.zIncrementSpin.setObjectName("zIncrementSpin")
        self.gridLayout_3.addWidget(self.zIncrementSpin, 5, 1, 1, 1)
        self.zCommandSpin = QtGui.QDoubleSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zCommandSpin.sizePolicy().hasHeightForWidth())
        self.zCommandSpin.setSizePolicy(sizePolicy)
        self.zCommandSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.zCommandSpin.setBaseSize(QtCore.QSize(0, 25))
        self.zCommandSpin.setSuffix(" mm")
        self.zCommandSpin.setMinimum(-400.0)
        self.zCommandSpin.setMaximum(400.0)
        self.zCommandSpin.setObjectName("zCommandSpin")
        self.gridLayout_3.addWidget(self.zCommandSpin, 5, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(218, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(218, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 4)
        self.moveButton = QtGui.QPushButton(Form)
        self.moveButton.setObjectName("moveButton")
        self.gridLayout_3.addWidget(self.moveButton, 6, 0, 1, 5)
        self.xPositionSpin = QtGui.QDoubleSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xPositionSpin.sizePolicy().hasHeightForWidth())
        self.xPositionSpin.setSizePolicy(sizePolicy)
        self.xPositionSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.xPositionSpin.setBaseSize(QtCore.QSize(0, 25))
        self.xPositionSpin.setReadOnly(True)
        self.xPositionSpin.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.xPositionSpin.setMinimum(-400.0)
        self.xPositionSpin.setMaximum(400.0)
        self.xPositionSpin.setObjectName("xPositionSpin")
        self.gridLayout_3.addWidget(self.xPositionSpin, 1, 2, 1, 1)
        self.yPositionSpin = QtGui.QDoubleSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yPositionSpin.sizePolicy().hasHeightForWidth())
        self.yPositionSpin.setSizePolicy(sizePolicy)
        self.yPositionSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.yPositionSpin.setBaseSize(QtCore.QSize(0, 25))
        self.yPositionSpin.setReadOnly(True)
        self.yPositionSpin.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.yPositionSpin.setMinimum(-400.0)
        self.yPositionSpin.setMaximum(400.0)
        self.yPositionSpin.setObjectName("yPositionSpin")
        self.gridLayout_3.addWidget(self.yPositionSpin, 3, 2, 1, 1)
        self.zPositionSpin = QtGui.QDoubleSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zPositionSpin.sizePolicy().hasHeightForWidth())
        self.zPositionSpin.setSizePolicy(sizePolicy)
        self.zPositionSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.zPositionSpin.setBaseSize(QtCore.QSize(0, 25))
        self.zPositionSpin.setReadOnly(True)
        self.zPositionSpin.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.zPositionSpin.setMinimum(-400.0)
        self.zPositionSpin.setMaximum(400.0)
        self.zPositionSpin.setObjectName("zPositionSpin")
        self.gridLayout_3.addWidget(self.zPositionSpin, 5, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 7, 0, 1, 4)
        self.positionLabel = QtGui.QLabel(Form)
        self.positionLabel.setObjectName("positionLabel")
        self.gridLayout_3.addWidget(self.positionLabel, 0, 2, 1, 1)
        self.xLaunchButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xLaunchButton.sizePolicy().hasHeightForWidth())
        self.xLaunchButton.setSizePolicy(sizePolicy)
        self.xLaunchButton.setMinimumSize(QtCore.QSize(25, 25))
        self.xLaunchButton.setMaximumSize(QtCore.QSize(25, 25))
        self.xLaunchButton.setBaseSize(QtCore.QSize(25, 25))
        self.xLaunchButton.setObjectName("xLaunchButton")
        self.gridLayout_3.addWidget(self.xLaunchButton, 1, 4, 1, 1)
        self.yLaunchButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yLaunchButton.sizePolicy().hasHeightForWidth())
        self.yLaunchButton.setSizePolicy(sizePolicy)
        self.yLaunchButton.setMinimumSize(QtCore.QSize(25, 25))
        self.yLaunchButton.setMaximumSize(QtCore.QSize(25, 25))
        self.yLaunchButton.setBaseSize(QtCore.QSize(25, 25))
        self.yLaunchButton.setObjectName("yLaunchButton")
        self.gridLayout_3.addWidget(self.yLaunchButton, 3, 4, 1, 1)
        self.zLabelButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zLabelButton.sizePolicy().hasHeightForWidth())
        self.zLabelButton.setSizePolicy(sizePolicy)
        self.zLabelButton.setMinimumSize(QtCore.QSize(25, 25))
        self.zLabelButton.setMaximumSize(QtCore.QSize(25, 25))
        self.zLabelButton.setBaseSize(QtCore.QSize(25, 25))
        self.zLabelButton.setObjectName("zLabelButton")
        self.gridLayout_3.addWidget(self.zLabelButton, 5, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stopButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(0, 100))
        self.stopButton.setBaseSize(QtCore.QSize(0, 25))
        self.stopButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Arrow/Stop2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon8)
        self.stopButton.setIconSize(QtCore.QSize(90, 90))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_4.addWidget(self.stopButton)
        self.originButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.originButton.sizePolicy().hasHeightForWidth())
        self.originButton.setSizePolicy(sizePolicy)
        self.originButton.setMinimumSize(QtCore.QSize(0, 100))
        self.originButton.setBaseSize(QtCore.QSize(0, 25))
        self.originButton.setDefault(False)
        self.originButton.setFlat(False)
        self.originButton.setObjectName("originButton")
        self.horizontalLayout_4.addWidget(self.originButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.topLabel.setBuddy(self.upPushButton)
        self.leftLabel.setBuddy(self.rightPushButton)
        self.rightLabel.setBuddy(self.leftPushButton)
        self.bottomLabel.setBuddy(self.downPushbutton)
        self.zTopLabel.setBuddy(self.minusZPushButton)
        self.zBottomLabel.setBuddy(self.plusZPushButton)
        self.incrementLabel.setBuddy(self.xIncrementSpin)
        self.commandedLabel.setBuddy(self.xCommandSpin)
        self.xLabel.setBuddy(self.xIncrementSpin)
        self.yLabel.setBuddy(self.yIncrementSpin)
        self.zLabel.setBuddy(self.zIncrementSpin)
        self.positionLabel.setBuddy(self.xPositionSpin)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.messageEdit.setText(QtGui.QApplication.translate("Form", "Move the Carriage and Z axis to the Print Origin. ", None, QtGui.QApplication.UnicodeUTF8))
        self.topLabel.setText(QtGui.QApplication.translate("Form", "X-", None, QtGui.QApplication.UnicodeUTF8))
        self.upPushButton.setShortcut(QtGui.QApplication.translate("Form", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.leftLabel.setText(QtGui.QApplication.translate("Form", "Y-", None, QtGui.QApplication.UnicodeUTF8))
        self.rightPushButton.setShortcut(QtGui.QApplication.translate("Form", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.rightLabel.setText(QtGui.QApplication.translate("Form", "Y+", None, QtGui.QApplication.UnicodeUTF8))
        self.downPushbutton.setShortcut(QtGui.QApplication.translate("Form", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomLabel.setText(QtGui.QApplication.translate("Form", "X+", None, QtGui.QApplication.UnicodeUTF8))
        self.leftPushButton.setShortcut(QtGui.QApplication.translate("Form", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.toOriginButton.setText(QtGui.QApplication.translate("Form", "Move To Origin", None, QtGui.QApplication.UnicodeUTF8))
        self.zTopLabel.setText(QtGui.QApplication.translate("Form", "Z-", None, QtGui.QApplication.UnicodeUTF8))
        self.minusZPushButton.setShortcut(QtGui.QApplication.translate("Form", "PgUp", None, QtGui.QApplication.UnicodeUTF8))
        self.plusZPushButton.setShortcut(QtGui.QApplication.translate("Form", "PgDown", None, QtGui.QApplication.UnicodeUTF8))
        self.incrementLabel.setText(QtGui.QApplication.translate("Form", "Increment", None, QtGui.QApplication.UnicodeUTF8))
        self.commandedLabel.setText(QtGui.QApplication.translate("Form", "Commanded", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.yLabel.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.zLabel.setText(QtGui.QApplication.translate("Form", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.moveButton.setText(QtGui.QApplication.translate("Form", "Move Carriage to Commanded", None, QtGui.QApplication.UnicodeUTF8))
        self.positionLabel.setText(QtGui.QApplication.translate("Form", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.xLaunchButton.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.yLaunchButton.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.zLabelButton.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.originButton.setText(QtGui.QApplication.translate("Form", "Set Origin", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
