# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MotorDialog.ui'
#
# Created: Wed Jul 13 17:19:06 2011
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(228, 275)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.motorLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.motorLabel.setFont(font)
        self.motorLabel.setObjectName("motorLabel")
        self.horizontalLayout_3.addWidget(self.motorLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.velocityLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.velocityLabel.setFont(font)
        self.velocityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.velocityLabel.setObjectName("velocityLabel")
        self.verticalLayout.addWidget(self.velocityLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.velocitySlider = QtGui.QSlider(Dialog)
        self.velocitySlider.setMinimumSize(QtCore.QSize(100, 40))
        self.velocitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.velocitySlider.setObjectName("velocitySlider")
        self.horizontalLayout.addWidget(self.velocitySlider)
        self.velocitySpin = QtGui.QDoubleSpinBox(Dialog)
        self.velocitySpin.setMinimumSize(QtCore.QSize(100, 40))
        self.velocitySpin.setObjectName("velocitySpin")
        self.horizontalLayout.addWidget(self.velocitySpin)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.accelerationLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.accelerationLabel.setFont(font)
        self.accelerationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.accelerationLabel.setObjectName("accelerationLabel")
        self.verticalLayout_2.addWidget(self.accelerationLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.accelerationSlider = QtGui.QSlider(Dialog)
        self.accelerationSlider.setMinimumSize(QtCore.QSize(100, 40))
        self.accelerationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.accelerationSlider.setObjectName("accelerationSlider")
        self.horizontalLayout_2.addWidget(self.accelerationSlider)
        self.accelerationSpin = QtGui.QDoubleSpinBox(Dialog)
        self.accelerationSpin.setMinimumSize(QtCore.QSize(100, 40))
        self.accelerationSpin.setSuffix(" mm/s^2")
        self.accelerationSpin.setObjectName("accelerationSpin")
        self.horizontalLayout_2.addWidget(self.accelerationSpin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.reverseCheckButton = QtGui.QCheckBox(Dialog)
        self.reverseCheckButton.setMinimumSize(QtCore.QSize(0, 40))
        self.reverseCheckButton.setObjectName("reverseCheckButton")
        self.verticalLayout_3.addWidget(self.reverseCheckButton)
        self.okButton = QtGui.QPushButton(Dialog)
        self.okButton.setObjectName("okButton")
        self.verticalLayout_3.addWidget(self.okButton)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL("clicked()"), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.motorLabel.setText(QtGui.QApplication.translate("Dialog", "Motor Name", None, QtGui.QApplication.UnicodeUTF8))
        self.velocityLabel.setText(QtGui.QApplication.translate("Dialog", "Velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.velocitySpin.setSuffix(QtGui.QApplication.translate("Dialog", " mm/s", None, QtGui.QApplication.UnicodeUTF8))
        self.accelerationLabel.setText(QtGui.QApplication.translate("Dialog", "Acceleration", None, QtGui.QApplication.UnicodeUTF8))
        self.reverseCheckButton.setText(QtGui.QApplication.translate("Dialog", "Reverse", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Dialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))

